import type { Metadata } from 'next'
import NavBar from '@/components/NavBar'
import { montserrat } from '@/fonts'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-black text-white container`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
